### ISSUE TITLE
Volume panel isn't got a full weight

### ISSUE THREAD

**Issue by LKc1949** [wasdennnoch/AndroidN-ify#185]
![screenshot_20160512-132208](https://cloud.githubusercontent.com/assets/17155723/15204871/232c9c50-17d8-11e6-9ceb-219462b875bd.png)
Using Darkobas MM , with 480dpi .
Has already enabled this feature but still not work(neither enable nor disable is work)

**Comment by vlw** [comment]
It fixed with 5dd89576a08f0a6376b6a1ecf9e48a210684861e

**Comment by vlw** [comment]
Compile from latest sources

**Comment by vlw** [comment]
[app-debug.apk.zip](https://github.com/wasdennnoch/AndroidN-ify/files/260663/app-debug.apk.zip) try to install this

**Comment by LKc1949** [comment]
But i still face it even on the latest build 95
[xposed_error_20160512_134137.txt](https://github.com/wasdennnoch/AndroidN-ify/files/260666/xposed_error_20160512_134137.txt)

**Comment by LKc1949** [comment]
![screenshot_20160512-134445](https://cloud.githubusercontent.com/assets/17155723/15205187/c5c3ae02-17da-11e6-89a3-9cb4d9d35fc4.png)
Not work either

**Comment by BlackGhost12** [comment]
![screenshot_2016-05-16-18-33-59](https://cloud.githubusercontent.com/assets/19236621/15294455/f7a998f6-1b94-11e6-8212-192a24ba4f42.png)
![screenshot_2016-05-16-18-34-23](https://cloud.githubusercontent.com/assets/19236621/15294461/fdc394c6-1b94-11e6-9f42-2423caacccad.png)

**Comment by BlackGhost12** [comment]
fixed 😀

**Comment by wasdennnoch** [comment]
@LKc1949 fixed for you too?

**Comment by wasdennnoch** [comment]
Because there are no negative updates here I'll close it.
