### ISSUE TITLE
A lot of errors when I tap on clock

### ISSUE THREAD

**Issue by ja-som** [wasdennnoch/AndroidN-ify#578]
Is it possible to add option to disable "Header clock click"?

Thanks

Xposed log:
http://pastebin.com/KPJsK9XQ

**Comment by wasdennnoch** [comment]
They should be fixed now (and weren't clock related :P). Why should I add that option?

**Comment by ja-som** [comment]
Thanks :)
I use same feature in Gravity Box module, sometimes it works, sometimes not, and when I disable it in Gravity Box, then it does not work and I have some error in Xposed log...
But, maybe I was confused with all those errors, maybe it will be OK now, I will try it ;)
Thanks 👍

**Comment by wasdennnoch** [comment]
The errors were letated to a missing resource and class that some ROMs removed, I found no clock related errors ;)

**Comment by ja-som** [comment]
I will use same place to report...
Updated to build450, clock click seems to work as it should, but I still have some errors in the log, probably again not related to clock feature, because errors are there right after reboot.

https://drive.google.com/file/d/0B0bWVvdcNSQlWS1YTGYxaEN5MHc/view?usp=drivesdk

**Comment by wasdennnoch** [comment]
They are related to the experimental features.
