### ISSUE TITLE
system ui Crash on boot Build #173

### ISSUE THREAD

**Issue by Teblakuda** [wasdennnoch/AndroidN-ify#966]
Device: Blu life one x 2016 (L0070UU)
Phone crashes on on build #173 after it boots up. Last working build for my device from what i have tried was #144.
[LogcatN#173.txt](https://github.com/wasdennnoch/AndroidN-ify/files/491244/LogcatN.173.txt)

**Comment by wasdennnoch** [comment]
There is no crash i the log, but please test the newest build (experimental builds are discontinued, the newest build is 693 I think), I fixed a bunch of crashes there.

**Comment by Teblakuda** [comment]
Hi, thanks for the response.
You said that their was no crash, maybe I took the logcat wrong? Is this the correct command?
Adb logcat -d > logcat.txt
Thanks again
Sent from my BLU smartphone device
On Sep 27, 2016 3:02 PM, MrWasdennnoch <notifications@github.com> wrote:
There is no crash i the log, but please test the newest build (experimental builds are discontinued, the newest build is 693 I think), I fixed a bunch of crashes there.

**Comment by wasdennnoch** [comment]
adb logcat -v time formats it better. But even just logcat works. Make sure to record while the SystemUI crashes (dismiss the crash dialog at least once).

**Comment by Teblakuda** [comment]
i tried #696 and the systemui still crashes. here is a proper logcat.
[logcat#696.txt](https://github.com/wasdennnoch/AndroidN-ify/files/500824/logcat.696.txt)

**Comment by Teblakuda** [comment]
[System UI_5.1.apk.zip](https://github.com/wasdennnoch/AndroidN-ify/files/511361/System.UI_5.1.apk.zip)

**Comment by wasdennnoch** [comment]
Does the crash still happen?

**Comment by wasdennnoch** [comment]
Please install this version and post your Xposed log: http://www.mediafire.com/file/nzb2u1q1huqzupt/Android_N-ify_debug_log_setMobileDataIndicators.apk

**Comment by Teblakuda** [comment]
[log.txt](https://github.com/wasdennnoch/AndroidN-ify/files/570221/log.txt)
Here is log for the crash

**Comment by Teblakuda** [comment]
Hey,  I just tried build #758 and it worked.  Everything seems to be working. Thanks for all your efforts. You can close this if you want or should I, though I don't know how :)
